# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  inventory:
    restart: unless-stopped
    healthcheck:
      test: >
        curl -f -X POST http://localhost:8080/graphql
        -H "Content-Type: application/json"
        --data '{ "query": "{ productItems{totalCount} }" }' || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    build:
      context: ./
    environment:
      DATABASE_URI: mongodb://inventory-db:27017
    depends_on:
      - inventory-db
  inventory-db:
    image: mongo:6.0
    hostname: inventory-db
    restart: always
    volumes:
      - inventory-db-data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
  mongosetup:
    image: mongo:6.0
    depends_on:
      - inventory-db
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 10 && mongosh --host inventory-db:27017 --eval 'rs.initiate()'"]
  inventory-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:inventory"
    command:
      [
        "./daprd",
        "--app-id",
        "inventory",
        "--app-port",
        "8080",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]

volumes:
  inventory-db-data: