services:
  inventory:
    extends:
      file: docker-compose-base.yaml
      service: inventory
    ports:
      - 8080:8080
    build:
      context: ./
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container src/app
    # reflect file changes from host to container
    # maps schema to reflect changes in the container
    volumes:
      - .:/src/inventory
      - /src/inventory/node_modules
      - ./src/inventory.gql:/src/inventory/src/inventory.gql
    command: npm run start:dev
  inventory-db:
    extends:
      file: docker-compose-base.yaml
      service: inventory-db
    ports:
      - "27017:27017"
  mongosetup:
    extends:
      file: docker-compose-base.yaml
      service: mongosetup
  inventory-dapr:
    extends:
      file: docker-compose-base.yaml
      service: inventory-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006
volumes:
  inventory-db-data: