name: Update GraphQL schema

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  schema:
    name: Update GraphQL schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "misarch/schemas"
          path: "schemas"
      - name: Save graphql schemas
        run: |
          cp ./src/inventory.gql ./schemas/inventory.graphql
          cp ./src/inventory-unfederated.gql ./schemas/inventory-unfederated.graphql
      - uses: peter-evans/create-pull-request@v5
        with:
          path: ./schemas
          commit-message: Update inventory schema
          branch: update/inventory
          token: ${{ secrets.SCHEMAS_PUSH_SECRET }}